### ISSUE TITLE
make "package" configurable

### ISSUE THREAD

**Issue by dsschult** [WIPACrepo/wipac-dev-py-setup-action#2]
Either allow the package(s) to be specified as an option, or add dirs that should be ignored (like `tests`).

**Comment by ric-evans** [comment]
The current mechanism uses `setup_tools`' `find:` directive to bundle/publish all the packages in the root dir. That's not configurable AFAIK. From its perspective, it's okay to have multiple packages, but it would mean publishing unintended packages (like tests) to clients via pip.

The guardrail which produces an error on the GH action prevents this scenario. Now what we could do in the action itself is temporarily alter the repo dir tree, kick out the not-to-be-published packages. Then, publish. It depends if we want to blacklist or whitelist.

**Comment by dsschult** [comment]
Apparently `setup_tools` is configurable for this:
https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#finding-simple-packages
```
[options]
packages = find:

[options.packages.find]
include = pkg*
exclude = additional
```
Note that the [default exclude list](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#flat-layout) takes care of these things with automatic discovery, but not if you use manual discovery with `find:`.

Note that their alternative is using a "src layout" where the python src is in a directory called `src`

**Comment by ric-evans** [comment]
Great! That would be an easy fix, at least for just ignoring tests: `*tests`. There may be a regex corner case out there.

Of course, there's the pattern that one pip package should contain just one python package. So, manually listing the package name would not be bad (no `find:`), but would require an extra attribute for `[wipac:cicd_setup_builder]`. Then again, this could be a list attribute.
